---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine

- name: Webserver configuration
  hosts: drei.personaltelco.net,turn.personaltelco.net

  roles:
    - rails
    - webserver
