---
- name: Install Rails application server packages
  become: yes
  apt:
    state: present
    name:
      - autoconf
      - bison
      - build-essential
      - git
      - graphviz
      - imagemagick
      - libffi-dev
      - libgdbm-dev
      - libmagickwand-6.q16-dev
      - libncurses5-dev
      - libpq-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - nodejs
      - postgresql
      - python-psycopg2
      - yarn
      - zlib1g-dev
