---
- name: Install postgresql package
  become: yes
  apt: name=postgresql state=present

- name: Install graphviz package
  become: yes
  apt: name=graphviz state=present

- name: Install nodejs package
  become: yes
  apt: name=nodejs state=present

- name: Install python-psycopg2 package
  become: yes
  apt: name=python-psycopg2 state=present

- name: Install yarn package
  become: yes
  apt: name=yarn state=present

- name: Install git package
  become: yes
  apt: name=git state=present

- name: Install autoconf package
  become: yes
  apt: name=autoconf state=present

- name: Install bison package
  become: yes
  apt: name=bison state=present

- name: Install build-essential package
  become: yes
  apt: name=build-essential state=present

- name: Install imagemagick package
  become: yes
  apt: name=imagemagick state=present

- name: Install libssl-dev package
  become: yes
  apt: name=libssl-dev state=present

- name: Install libyaml-dev package
  become: yes
  apt: name=libyaml-dev state=present

- name: Install libreadline6-dev package
  become: yes
  apt: name=libreadline6-dev state=present

- name: Install zlib1g-dev package
  become: yes
  apt: name=zlib1g-dev state=present

- name: Install libncurses5-dev package
  become: yes
  apt: name=libncurses5-dev state=present

- name: Install libffi-dev package
  become: yes
  apt: name=libffi-dev state=present

- name: Install libgdbm-dev package
  become: yes
  apt: name=libgdbm-dev state=present

- name: Install libpq-dev package
  become: yes
  apt: name=libpq-dev state=present

- name: Install libmagickwand-6.q16-dev package
  become: yes
  apt: name=libmagickwand-6.q16-dev state=present
