---
- name: Accept oracle license
  become: yes
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Accept oracle license
  become: yes
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: seen

- name: Install Rails application server packages
  become: yes
  apt:
    state: present
    name:
      - autoconf
      - bison
      - build-essential
      - elasticsearch
      - graphviz
      - imagemagick
      - libffi-dev
      - libgdbm-dev
      - libmagickwand-6.q16-dev
      - libncurses5-dev
      - libpq-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - nodejs
      - oracle-java8-installer
      - postgresql
      - python-psycopg2
      - yarn
      - zlib1g-dev

- name: Create deploy user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: deploy
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER

- name: Copy database backup script
  become: yes
  copy:
    src: pg_backup.sh
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: 0755

- name: Schedule database backup
  become: yes
  cron:
    name: database backup
    cron_file: pg_backup
    user: root
    job: /usr/local/sbin/pg_backup.sh
    minute: '0'
    hour: '1'

- name: Create deploy user
  become: yes
  user:
    name: deploy
    comment: Application Deployment
    shell: /bin/bash
    groups: sudo

- name: Copy the SSH authorized_keys file for the deploy user
  become: yes
  authorized_key:
    user: deploy
    key: https://raw.githubusercontent.com/personaltelco/ptp-openwrt-files/master/etc/dropbear/authorized_keys

- name: Copy application-specific configuration
  become: yes
  copy:
    src: apps/
    dest: /etc/rails
    owner: deploy
    group: deploy
    mode: 0600

- name: Install rbenv for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/deploy/.rbenv
    version: master

- name: Install rbenv-sudo for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/dcarley/rbenv-sudo.git
    dest: /home/deploy/.rbenv/plugins/rbenv-sudo
    version: master

- name: Install ruby-build for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/deploy/.rbenv/plugins/ruby-build
    version: master

- name: Copy the bashrc for the deploy user
  become: yes
  copy: src=bashrc dest=/home/deploy/.bashrc owner=deploy group=deploy

- name: Copy the profile for the deploy user
  become: yes
  copy: src=profile dest=/home/deploy/.profile owner=deploy group=deploy

- name: Install Ruby 2.6.3 for the deploy user
  become: yes
  become_user: deploy
  shell: /home/deploy/.rbenv/bin/rbenv install -s 2.6.3
  args:
    creates: /home/deploy/.rbenv/versions/2.6.3

- name: Install Bundler for the deploy user
  become: yes
  become_user: deploy
  shell: RBENV_VERSION=2.6.3 /home/deploy/.rbenv/shims/gem install bundler
  args:
    creates: /home/deploy/.rbenv/versions/2.6.3/bin/bundler

- name: Install Foreman for the deploy user
  become: yes
  become_user: deploy
  shell: RBENV_VERSION=2.6.3 /home/deploy/.rbenv/shims/gem install foreman
  args:
    creates: /home/deploy/.rbenv/versions/2.6.3/bin/foreman

- name: Create /srv/rails
  become: yes
  file:
    path: /srv/rails
    state: directory
    mode: 0755
    owner: deploy
    group: deploy

- name: Copy Elasticsearch configuration
  become: yes
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Copy Postgres configuration
  become: yes
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/9.6/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgresql

- name: Create cwnmyr user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: cwnmyr
    password: cwnmyr
    encrypted: yes

- name: Create cwnmyr database in Postgres
  become: yes
  become_user: postgres
  postgresql_db:
    name: cwnmyr
    owner: cwnmyr
    encoding: UTF-8
