---
- name: Install postgresql package
  become: yes
  pacman: name=postgresql state=present

- name: Initialize postgresql cluster
  become: yes
  become_user: postgres
  command: initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
  args:
    creates: /var/lib/postgres/data/PG_VERSION

- name: Enable and start the postgresql service
  become: yes
  service: name=postgresql enabled=yes state=started

- name: Install graphviz package
  become: yes
  pacman: name=graphviz state=present

- name: Install nodejs package
  become: yes
  pacman: name=nodejs state=present

- name: Install phantomjs package
  become: yes
  pacman: name=phantomjs state=present

- name: Install yarn package
  become: yes
  pacman: name=yarn state=present

- name: Install python-psycopg2 package
  become: yes
  pacman: name=python-psycopg2 state=present

- name: Install autoconf package
  become: yes
  pacman: name=autoconf state=present

- name: Install bison package
  become: yes
  pacman: name=bison state=present

- name: Install gcc package
  become: yes
  pacman: name=gcc state=present

- name: Install openssl-1.0 package
  become: yes
  pacman: name=openssl-1.0 state=present

- name: Install libyaml package
  become: yes
  pacman: name=libyaml state=present

- name: Install readline package
  become: yes
  pacman: name=readline state=present

- name: Install zlib package
  become: yes
  pacman: name=zlib state=present

- name: Install ncurses package
  become: yes
  pacman: name=ncurses state=present

- name: Install libffi package
  become: yes
  pacman: name=libffi state=present

- name: Install gdbm package
  become: yes
  pacman: name=gdbm state=present

- name: Install imagemagick6 package
  become: yes
  pacman: name=imagemagick6 state=present
