---
- name: restart elasticsearch
  become: yes
  service: name=elasticsearch state=restarted enabled=yes

- name: restart postgresql
  become: yes
  service: name=postgresql state=restarted enabled=yes
