---
- name: Copy sudo configuration
  become: yes
  copy: src=nopasswd.sudoers dest=/etc/sudoers.d/nopasswd mode=0440

- name: Create sudo group
  become: yes
  group:
    name: sudo
    state: present

- name: Apply sudo group
  become: yes
  user:
    name: keegan
    groups: sudo

- name: Add elasticsearch APT key
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add yarn APT key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Copy APT sources
  become: yes
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Update and upgrade Debian packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install machine packages
  become: yes
  apt:
    state: present
    name:
      - apt-listchanges
      - curl
      - deborphan
      - emacs
      - file
      - finger
      - git
      - lftp
      - mlocate
      - nmap
      - screen
      - tcpdump
      - unzip
