---
- name: Copy sudo configuration
  become: yes
  copy: src=nopasswd.sudoers dest=/etc/sudoers.d/nopasswd mode=0440

- name: Create sudo group
  become: yes
  group:
    name: sudo
    state: present

- name: Apply sudo group
  become: yes
  user:
    name: keegan
    groups: sudo

- name: Update and upgrade Debian packages
  become: yes
  apt: update_cache=yes upgrade=dist
  when: ansible_pkg_mgr == "apt"

- name: Update and upgrade Arch packages
  become: yes
  pacman: update_cache=yes upgrade=yes
  when: ansible_pkg_mgr == "pacman"

- name: Install bind-tools package on Arch
  become: yes
  pacman: name=bind-tools state=present
  when: ansible_pkg_mgr == "pacman"

- name: Install postfix package on Arch
  become: yes
  pacman: name=postfix state=present
  when: ansible_pkg_mgr == "pacman"

- name: Enable and start the postfix service
  become: yes
  service: name=postfix enabled=yes state=started
  when: ansible_pkg_mgr == "pacman"
