---
- name: Install nginx package on Debian
  become: yes
  apt: name=nginx state=present
  when: ansible_pkg_mgr == "apt"

- name: Install nginx package on Arch
  become: yes
  pacman: name=nginx state=present
  when: ansible_pkg_mgr == "pacman"

- name: Install certbot package on Debian
  become: yes
  apt: name=certbot state=present
  when: ansible_pkg_mgr == "apt"

- name: Install certbot package on Arch
  become: yes
  pacman: name=certbot state=present
  when: ansible_pkg_mgr == "pacman"

- name: Copy nginx configuration
  become: yes
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  when: ansible_pkg_mgr == "pacman"
  notify: restart nginx

- name: Generate Diffie-Hellman parameters for nginx
  become: yes
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: restart nginx

- name: Create /etc/nginx/sites-enabled
  become: yes
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: 0755
  notify: restart nginx

- name: Copy nginx virtual hosts
  become: yes
  copy: src=sites/ dest=/etc/nginx/sites-enabled
  notify: restart nginx
